"""
Compute cross-entropy (CE) loss of pre-trained models over curated safe/harmful responses.

For each model × environment × response_type (safe/harmful), computes the CE of
the model over the agent_message conditioned on the formatted prompt.  No training occurs.

Prompts stored in the curated files may have been formatted with or without a system
role (depending on which model generated them).  This script adapts the prompt to each
target model's tokenizer capabilities before computing CE.

Models are loaded in descending size order so OOM failures surface early.
Each model is fully unloaded before the next one is loaded.

Output:
    results_ablation/completions_restruct/ce_scores/{model_slug}/{env_name}_{type}.jsonl
Each line:
    {"idx": int, "step": int, "sample_index": int, "_seed": int,
     "src_model": str, "ce": float, "er_metric": int, "acc_metric": int}
"""

import gc
import json
import sys
from pathlib import Path
from typing import Optional

import torch
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

# ── repo root on path ────────────────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from llm_agent.environments.utils.formatting import wrap_between_tags
from llm_agent.utils.utils import ensure_chat_template, supports_system_role

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

# Sorted largest-first so OOM surfaces immediately
MODEL_NAMES = [
    "Qwen/Qwen1.5-0.5B-Chat",
    "Qwen/Qwen1.5-14B-Chat",
    "meta-llama/Llama-2-13b-chat-hf",
    "meta-llama/Meta-Llama-3-8B-Instruct",
    "google/gemma-1.1-7b-it",
    "meta-llama/Llama-2-7b-chat-hf",
    "Qwen/Qwen1.5-7B-Chat",
    "01-ai/Yi-6B-Chat",
    "Qwen/Qwen1.5-4B-Chat",
    "Qwen/Qwen1.5-1.8B-Chat",
    "google/gemma-1.1-2b-it",
]

TARGET_ENVS = ["therapy_talk", "action_advice", "political_qa"]
RESPONSE_TYPES = ["harmful", "safe"]

CURATED_BASE = Path("./results_ablation/completions_restruct")
CE_OUTPUT_BASE = CURATED_BASE / "ce_scores"


def model_to_slug(model_name: str) -> str:
    """Convert HF model path to filesystem-safe folder name."""
    return model_name.split("/")[-1].replace(".", "_").replace("-", "_")


# ─────────────────────────────────────────────────────────────────────────────
# Prompt adaptation
# ─────────────────────────────────────────────────────────────────────────────

def adapt_prompt_for_model(
    prompt_messages: list[dict],
    model_supports_system: bool,
) -> list[dict]:
    """
    Ensure the stored prompt is compatible with the target model's tokenizer.

    Two stored formats exist:
      A) First message has role="system"  → generated by a model with system support.
      B) First message role="user" with <system_instructions> tags  → no-system format.

    Adaptation rules:
      - Format A + model supports system  → use as-is.
      - Format A + model no system support → convert: wrap system content in
        <system_instructions> tags, prepend to first user message.
      - Format B (any model)             → use as-is; tags are harmless for models
        that do support system (the system context is in the user message).
    """
    if not prompt_messages:
        return prompt_messages

    first = prompt_messages[0]
    if first["role"] != "system":
        return prompt_messages  # already in wrapped format (Format B)

    if model_supports_system:
        return prompt_messages  # Format A, model can handle it

    # Format A → convert to Format B
    system_content = wrap_between_tags(first["content"].strip(), "system_instructions")
    delimiter = "\n### Start user message:\n"
    rest = prompt_messages[1:]

    if rest and rest[0]["role"] == "user":
        merged_content = system_content + delimiter + rest[0]["content"]
        return [{"role": "user", "content": merged_content}] + rest[1:]
    else:
        return [{"role": "user", "content": system_content}] + rest


# ─────────────────────────────────────────────────────────────────────────────
# CE computation
# ─────────────────────────────────────────────────────────────────────────────

def compute_ce(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    prompt_messages: list[dict],
    agent_message: str,
    model_supports_system: bool,
    device: torch.device,
) -> Optional[float]:
    """
    Compute mean cross-entropy over agent_message tokens given prompt_messages.

    Returns None if the completion tokenizes to zero tokens.
    """
    adapted = adapt_prompt_for_model(prompt_messages, model_supports_system)

    # Full sequence: prompt + assistant completion
    full_messages = adapted + [{"role": "assistant", "content": agent_message}]

    try:
        full_text = tokenizer.apply_chat_template(
            full_messages, tokenize=False, add_generation_prompt=False
        )
        prompt_text = tokenizer.apply_chat_template(
            adapted, tokenize=False, add_generation_prompt=True
        )
    except Exception as e:
        print(f"  [WARN] apply_chat_template failed: {e}")
        return None

    full_ids = tokenizer(full_text, return_tensors="pt").input_ids.to(device)
    prompt_ids = tokenizer(prompt_text, return_tensors="pt").input_ids.to(device)

    n_prompt = prompt_ids.shape[1]
    n_full = full_ids.shape[1]
    n_completion = n_full - n_prompt

    if n_completion <= 0:
        return None

    # Labels: -100 for prompt tokens (ignored in loss), real ids for completion
    labels = full_ids.clone()
    labels[0, :n_prompt] = -100

    with torch.no_grad():
        outputs = model(full_ids, labels=labels)

    return outputs.loss.item()


# ─────────────────────────────────────────────────────────────────────────────
# Model loading / unloading
# ─────────────────────────────────────────────────────────────────────────────

def load_model_and_tokenizer(
    model_name: str,
    device: torch.device,
) -> tuple[AutoModelForCausalLM, AutoTokenizer]:
    dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    print(f"\n  Loading tokenizer: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    tokenizer = ensure_chat_template(tokenizer, model_name)
    tokenizer.padding_side = "left"

    print(f"  Loading model ({dtype}) ...")
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=dtype,
        device_map="auto",
        trust_remote_code=True,
    )
    model.eval()
    return model, tokenizer


def unload_model(model: AutoModelForCausalLM, tokenizer: AutoTokenizer) -> None:
    del model, tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


# ─────────────────────────────────────────────────────────────────────────────
# Data helpers
# ─────────────────────────────────────────────────────────────────────────────

def load_curated(env_name: str, response_type: str) -> list[dict]:
    path = CURATED_BASE / env_name / "curated_responses" / f"{response_type}_completions.json"
    if not path.exists():
        print(f"  [WARN] Not found: {path}")
        return []
    with open(path) as f:
        return json.load(f)


def output_path(model_slug: str, env_name: str, response_type: str) -> Path:
    return CE_OUTPUT_BASE / model_slug / f"{env_name}_{response_type}.jsonl"


# ─────────────────────────────────────────────────────────────────────────────
# Main evaluation loop
# ─────────────────────────────────────────────────────────────────────────────

def run_ce_evaluation(
    model_names: list[str] = MODEL_NAMES,
    env_names: list[str] = TARGET_ENVS,
    response_types: list[str] = RESPONSE_TYPES,
    skip_existing: bool = True,
) -> None:
    """
    Outer loop: model → (env × type).  One model load per model; full unload after.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    for model_name in model_names:
        slug = model_to_slug(model_name)
        print(f"\n{'='*60}")
        print(f"Model: {model_name}  ({slug})")

        # Check if all outputs already exist (allow resuming)
        tasks = []
        for env_name in env_names:
            for rtype in response_types:
                out = output_path(slug, env_name, rtype)
                if skip_existing and out.exists():
                    print(f"  [SKIP] {env_name}/{rtype} already done")
                else:
                    tasks.append((env_name, rtype))

        if not tasks:
            print("  All tasks already complete, skipping model load.")
            continue

        model, tokenizer = load_model_and_tokenizer(model_name, device)
        model_supports_system = supports_system_role(tokenizer)
        print(f"  Supports system role: {model_supports_system}")

        for env_name, rtype in tasks:
            samples = load_curated(env_name, rtype)
            if not samples:
                continue

            out = output_path(slug, env_name, rtype)
            out.parent.mkdir(parents=True, exist_ok=True)

            print(f"  [{env_name}/{rtype}] {len(samples)} samples", flush=True)
            results = []

            for idx, rec in enumerate(tqdm(samples, desc=f"  {env_name}/{rtype}", leave=False)):
                ce = compute_ce(
                    model=model,
                    tokenizer=tokenizer,
                    prompt_messages=rec["prompt"],
                    agent_message=rec["agent_message"],
                    model_supports_system=model_supports_system,
                    device=device,
                )
                results.append({
                    "idx":          idx,
                    "step":         rec.get("step"),
                    "sample_index": rec.get("sample_index"),
                    "_seed":        rec.get("_seed"),
                    "src_model":    rec.get("model_name"),
                    "ce":           ce,
                    "er_metric":    rec.get("er_metric"),
                    "acc_metric":   rec.get("acc_metric"),
                })

            with open(out, "w") as f:
                for r in results:
                    f.write(json.dumps(r) + "\n")

            n_ok = sum(1 for r in results if r["ce"] is not None)
            mean_ce = sum(r["ce"] for r in results if r["ce"] is not None) / max(n_ok, 1)
            print(f"    → saved {len(results)} records (mean CE={mean_ce:.3f}, {len(results)-n_ok} skipped)")

        unload_model(model, tokenizer)
        print(f"  Model {slug} unloaded.")


if __name__ == "__main__":
    run_ce_evaluation()
